network:
  region: "ap-southeast-2"
  availability_zones:
    - "ap-southeast-2a"
    - "ap-southeast-2b"
    - "ap-southeast-2c"
  deployment_name: "test"
  vpc_cidr: "10.203.0.0/16"
  public_subnets: 
    - "10.203.10.0/24"
  private_subnets: 
    - "10.203.20.0/24"
  enable_http_access: true
  enable_vpc: true
  enable_tgw: true
  